- id: check-whitespace-between-cn-and-en-char
  name: CN-[whitespace]-EN checker
  description: Ensure Chinese and English characters are separated by a space.
  entry: check-whitespace-between-cn-and-en-char
  language: python
  types: [text]
- id: insert-whitespace-between-cn-and-en-char
  name: CN-[whitespace]-EN fixer
  description: Insert a space between Chinese and English characters automatically.
  entry: insert-whitespace-between-cn-and-en-char
  language: python
  types: [text]
- id: check-case-conflict
  name: Case-insensitive filesystem conflict checker
  description: Check for filename conflicts on case-insensitive filesystems (APFS, NTFS).
  entry: check-case-conflict
  language: python
  pass_filenames: true
