repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/ShigureLab/dochooks
    rev: 97d63894296322f5064c05fa579f92aefad3f4f7
    hooks:
      - id: check-whitespace-between-cn-and-en-char
